=== yuva29/xml_xqueries/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp2 (x64) (http://www.altova.com) by Yuva (None) -->
<!-- xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns=" http://www.company.org" targetNamespace=" http://www.company.org" xmlns="http://www.company.org" elementFormDefault="qualified">-->

<!--<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace=" http://www.company.org" xmlns="http://www.company.org" elementFormDefault="qualified">-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="Departments">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="Department" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="deptId">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Z][A-Z][A-Z]"></xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="deptName" type="xs:string"></xs:element>
							<xs:element name="deptAddr" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				</xs:sequence>
				</xs:complexType>
				</xs:element>
				<xs:element name="Employees" minOccurs="0">
				<xs:complexType>
				<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="empId" type="xs:integer"></xs:element>
							<xs:element name="empName" type="xs:string"></xs:element>
							<xs:element name="empPhone">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{4}"></xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="empOffice"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			 	</xs:sequence>
				</xs:complexType>
				</xs:element>
				<xs:element name="Divisions" minOccurs="0">
				<xs:complexType>			
				<xs:sequence>
				<xs:element name="Division" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="divId" type="xs:string"></xs:element>
							<xs:element name="divName" type="xs:string"></xs:element>
							<xs:element name="divPhone">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{4}"></xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="housedDeptId" type="xs:string"></xs:element>
							<xs:element name="managerEmpId" type="xs:integer"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
				</xs:complexType>
				</xs:element>		
				<xs:element name="WF" minOccurs="0">
				<xs:complexType>
				<xs:sequence>

				<xs:element name="WorksFor" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="divId" type="xs:string"></xs:element>
							<xs:element name="empId" type="xs:integer"></xs:element>
							<xs:element name="percentTime" type="xs:integer"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				</xs:sequence>
				</xs:complexType>				
				</xs:element>		
			</xs:sequence>
		</xs:complexType>
		<xs:key name="deptPK">
			<xs:selector xpath="Departments/Department/deptId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:key>
		<xs:key name="empPK">
			<xs:selector xpath="Employees/Employee/empId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:key>
		<xs:key name="divPK">
			<xs:selector xpath="Divisions/Division/divId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:key>
		<xs:keyref name="divDeptId" refer="deptPK">
			<xs:selector xpath="Divisions/Division/housedDeptId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:keyref>
		<xs:keyref name="divMgrId" refer="empPK">
			<xs:selector xpath="Divisions/Division/managerEmpId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:keyref>
		<xs:keyref name="wfDivId" refer="divPK">
			<xs:selector xpath="WF/WorksFor/divId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:keyref>
		<xs:keyref name="wfEmpId" refer="empPK">
			<xs:selector xpath="WF/WorksFor/empId"></xs:selector>
			<xs:field xpath="."></xs:field>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== yuva29/xml_xqueries/company.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Thu Nov 13 11:48:41 MST 2014 -->


<!-- xmlns="http://www.company.org"  xsi:schemaLocation="http://www.company.org schema.xsd" -->

<?xml-stylesheet type="text/xsl" href="company.xsl"?>
<Company xsi:noNamespaceSchemaLocation="company.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<!--<Company xmlns="http://www.company.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.company.org company.xsd">-->
	<Departments>
		<Department>
			<deptId>ADM</deptId>
			<deptName>Admin</deptName>
			<deptAddr>LA</deptAddr>
		</Department>
		<Department>
			<deptId>FIN</deptId>
			<deptName>Finance</deptName>
			<deptAddr>LA</deptAddr>
		</Department>
		<Department>
			<deptId>SER</deptId>
			<deptName>Services</deptName>
			<deptAddr>LA</deptAddr>
		</Department>
		<Department>
			<deptId>OPR</deptId>
			<deptName>Operations</deptName>
			<deptAddr>LA</deptAddr>
		</Department>
		<Department>
			<deptId>BUS</deptId>
			<deptName>Business</deptName>
			<deptAddr>LA</deptAddr>
		</Department>
	</Departments>
	<Employees>
		<Employee>
			<empId>1</empId>
			<empName>PSmith</empName>
			<empPhone>243-235-3253</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>2</empId>
			<empName>Wong</empName>
			<empPhone>224-234-9065</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>3</empId>
			<empName>Jack</empName>
			<empPhone>243-235-4566</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>4</empId>
			<empName>Anne</empName>
			<empPhone>324-876-3768</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>5</empId>
			<empName>Ben</empName>
			<empPhone>453-249-3275</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>6</empId>
			<empName>Monica</empName>
			<empPhone>935-487-3859</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>7</empId>
			<empName>Jennifer</empName>
			<empPhone>935-487-3869</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
		<Employee>
			<empId>8</empId>
			<empName>Mary</empName>
			<empPhone>932-487-3859</empPhone>
			<empOffice>LA</empOffice>
		</Employee>
	</Employees>
	<Divisions>
		<Division>
			<divId>div1</divId>
			<divName>HR</divName>
			<divPhone>346-232-3242</divPhone>
			<housedDeptId>ADM</housedDeptId>
			<managerEmpId>4</managerEmpId>
		</Division>
		<Division>
			<divId>div2</divId>
			<divName>Recruitment</divName>
			<divPhone>346-232-3243</divPhone>
			<housedDeptId>ADM</housedDeptId>
			<managerEmpId>1</managerEmpId>
		</Division>
		<Division>
			<divId>div3</divId>
			<divName>SysAd</divName>
			<divPhone>346-232-3244</divPhone>
			<housedDeptId>ADM</housedDeptId>
			<managerEmpId>3</managerEmpId>
		</Division>
		<Division>
			<divId>div4</divId>
			<divName>Payroll</divName>
			<divPhone>346-232-3245</divPhone>
			<housedDeptId>FIN</housedDeptId>
			<managerEmpId>5</managerEmpId>
		</Division>
		<Division>
			<divId>div5</divId>
			<divName>Accounting</divName>
			<divPhone>346-232-3246</divPhone>
			<housedDeptId>FIN</housedDeptId>
			<managerEmpId>5</managerEmpId>
		</Division>
		<Division>
			<divId>div6</divId>
			<divName>Networking</divName>
			<divPhone>346-232-3247</divPhone>
			<housedDeptId>SER</housedDeptId>
			<managerEmpId>2</managerEmpId>
		</Division>
		<Division>
			<divId>div7</divId>
			<divName>SaaS</divName>
			<divPhone>346-232-3248</divPhone>
			<housedDeptId>SER</housedDeptId>
			<managerEmpId>2</managerEmpId>
		</Division>
		<Division>
			<divId>div8</divId>
			<divName>Security</divName>
			<divPhone>346-232-3249</divPhone>
			<housedDeptId>SER</housedDeptId>
			<managerEmpId>1</managerEmpId>
		</Division>
		<Division>
			<divId>div9</divId>
			<divName>Convergence</divName>
			<divPhone>346-232-3250</divPhone>
			<housedDeptId>SER</housedDeptId>
			<managerEmpId>1</managerEmpId>
		</Division>
		<Division>
			<divId>div10</divId>
			<divName>Sales</divName>
			<divPhone>346-232-3251</divPhone>
			<housedDeptId>OPR</housedDeptId>
			<managerEmpId>1</managerEmpId>
		</Division>
		<Division>
			<divId>div11</divId>
			<divName>Marketing</divName>
			<divPhone>346-232-3252</divPhone>
			<housedDeptId>OPR</housedDeptId>
			<managerEmpId>4</managerEmpId>
		</Division>
		<Division>
			<divId>div12</divId>
			<divName>Engineering</divName>
			<divPhone>346-232-3253</divPhone>
			<housedDeptId>OPR</housedDeptId>
			<managerEmpId>4</managerEmpId>
		</Division>
		<Division>
			<divId>div13</divId>
			<divName>Business Development</divName>
			<divPhone>346-232-3254</divPhone>
			<housedDeptId>BUS</housedDeptId>
			<managerEmpId>1</managerEmpId>
		</Division>
		<Division>
			<divId>div14</divId>
			<divName>Business Analysis</divName>
			<divPhone>346-232-3255</divPhone>
			<housedDeptId>BUS</housedDeptId>
			<managerEmpId>1</managerEmpId>
		</Division>
	</Divisions>
	<WF>
		<WorksFor>
			<divId>div1</divId>
			<empId>4</empId>
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>4</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>4</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div13</divId>
			<empId>4</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div14</divId>
			<empId>4</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>5</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>5</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div4</divId>
			<empId>5</empId>
			<percentTime>50</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div5</divId>
			<empId>5</empId>
			<percentTime>30</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>3</empId>
			<percentTime>20</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>3</empId>
			<percentTime>20</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div8</divId>
			<empId>3</empId>
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>6</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>6</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div6</divId>
			<empId>6</empId>
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div7</divId>
			<empId>6</empId>
			<percentTime>20</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>1</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>1</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div6</divId>
			<empId>1</empId>
			<percentTime>15</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div8</divId>
			<empId>1</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div10</divId>
			<empId>1</empId>
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div13</divId>
			<empId>1</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div9</divId>
			<empId>1</empId>
			<percentTime>3</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div14</divId>
			<empId>1</empId>
			<percentTime>2</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>2</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>2</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div6</divId>
			<empId>2</empId>
			<percentTime>30</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div7</divId>
			<empId>2</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div1</divId>
			<empId>2</empId>
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div8</divId>
			<empId>2</empId>
			<percentTime>15</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div4</divId>
			<empId>2</empId>
			<percentTime>15</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div7</divId>
			<empId>7</empId>
			<percentTime>90</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>7</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>7</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div11</divId>
			<empId>8</empId>
			<percentTime>90</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div2</divId>
			<empId>8</empId>
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor>
			<divId>div3</divId>
			<empId>8</empId>
			<percentTime>5</percentTime>
		</WorksFor>
	</WF>
</Company>
